# Node config
node:
  # Meta
  name: 'ABT Node'
  description: 'Container of official ArcBlock blocklets'

  # Node wallet
  sk: '0xf80939b4ff688cd148ceab330b451683d41bb616b259507ae3e96a1188706d367efeabbebdc0cb49bcf865c77a15993d87245b124bbc5125d2c3997437d1fda3'
  pk: '0x7efeabbebdc0cb49bcf865c77a15993d87245b124bbc5125d2c3997437d1fda3'
  did: 'zNKgjyuEWQQqfuJcAVruPRHUaDD1PzcsAjaD'

  # Where to store ABT Node data
  dataDir: /Users/wangshijun/.abtnode

  # Node dashboard
  domain: 192.168.1.2
  port: 5554
  https: false

  # Node dashboard session secret
  secret: 'weilru4j2oi34u*(#U$IORQWRjk'

  # Owner info
  owner:
    pk: ''
    did: ''

blocklet:
  # On which port should blocklet process listen on, multiple blocklets will use different ports incremented from this config
  port: 5555

  # Where to fetch available blocklets
  registry: https://blocklet.arcblockio.cn
